# Generated by Django 3.2.9 on 2021-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Green Blog 17', max_length=255),
        ),
    ]
